# Generated by Django 3.2.11 on 2023-12-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231208_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_secure',
        ),
    ]
